package com.example.asc_guest.genericmusicapp;

import java.util.ArrayList;

/**
 * Responsible for creating and maintaining songs, artists, and genres.
 */
public class MusicPlayer {

    /**
     * Returns the song ArrayList.
     * @return ArrayList
     */
    public ArrayList<Song> songs(){
        return Song.getAll();
    }

    /**
     * Returns the genre ArrayList.
     * @return ArrayList
     */
    public ArrayList<Genre> genres(){
        return Genre.getAll();
    }

    /**
     * Returns the artist ArrayList.
     * @return ArrayList
     */
    public ArrayList<Artist> artists(){
        return Artist.getAll();
    }

    /**
     * Responsible for creating individual songs.
     * @see "https://think.cs.vt.edu/corgis/csv/music/music.html"
     */
    public MusicPlayer(){
        new Song("Casual",218.93179,"hip hop","I Didn't Mean To");
        new Song("The Box Tops",148.03546,"blue-eyed soul","Soul Deep");
        new Song("Sonora Santanera",177.47546,"salsa","Amor De Cabaret");
        new Song("Adam Ant",233.40363,"pop rock","Something Girls");
        new Song("Gob",209.60608,"pop punk","Face the Ashes");
        new Song("Jeff And Sheri Easter",267.7024,"southern gospel","The Moon And I (Ordinary Day Album Version)");
        new Song("Rated R",114.78159,"breakbeat","Keepin It Real (Skit)");
        new Song("Tweeterfriendly Music",189.57016,"post-hardcore","Drop of Rain");
        new Song("Planet P Project",269.81832,"new wave","Pink World");
        new Song("Clp",266.39628,"breakcore","Insatiable (Instrumental Version)");
        new Song("JennyAnyKind",218.77506,"alternative rock","Young Boy Blues");
        new Song("Wayne Watson",245.21098,"ccm","The Urgency (LP Version)");
        new Song("Andy Andy",226.35057,"bachata","La Culpa");
        new Song("Bob Azzam",191.84281,"chanson","Auguri Cha Cha");
        new Song("Lionel Richie",307.3824,"quiet storm","Tonight Will Be Alright");
        new Song("Blue Rodeo",491.12771,"country rock","Floating");
        new Song("Richard Souther",228.5971,"chill-out","High Tide");
        new Song("Faiz Ali Faiz",599.24853,"qawwali","Sohna Nee Sohna Data");
        new Song("Tesla",290.29832,"hard rock","Caught In A Dream");
        new Song("lextrical",165.69424,"indietronica","Synthetic Dream");
        new Song("Jimmy Wakely",151.84934,"classic country","Broken-Down Merry-Go-Round");
        new Song("Alice Stuart",220.78649,"electric blues","Kassie Jones");
        new Song("Elena",269.58322,"uk garage","Setanta matins");
        new Song("The Dillinger Escape Plan",207.77751,"math-core","Setting Fire to Sleeping Giants");
        new Song("SUE THOMPSON",124.86485,"pop rock","James (Hold The Ladder Steady)");
        new Song("Five Bolt Main",225.09669,"post-grunge","Made Like This (Live)");
        new Song("Clp",338.31138,"breakcore","Superconfidential");
        new Song("Tim Wilson",186.48771,"filk","I Think My Wife Is Running Around On Me (Taco Hell)");
        new Song("Willie Bobo",168.25424,"latin jazz","Spanish Grease");
        new Song("Faye Adams",156.39465,"jump blues","Crazy Mixed Up World");
        new Song("Terry Callier",342.56934,"soul jazz","Do You Finally Need A Friend");
        new Song("John Wesley",484.62322,"disco","The Emperor Falls");
        new Song("The Shangri-Las",164.80608,"doo-wop","Twist and Shout");
        new Song("Billie Jo Spears",133.32853,"classic country","It Makes No Difference Now");
        new Song("Mike Jones (Featuring CJ_ Mello & Lil' Bran)",173.66159,"rap","Laws Patrolling (Album Version)");
        new Song("Sierra Maestra",313.12934,"charanga","A?DA3nde va Chichi?");
        new Song("Butthole Surfers",450.84689,"noise rock","Barking Dogs (From Piouhgd)");
        new Song("Despina Vandi",303.09832,"dance pop","OUTE ENA EFHARISTO");
        new Song("Javier Navarrete",128.83546,"orchestra","Midnight Swim");
        new Song("Jacob Young",456.30649,"cool jazz","In A Subtle Way");
        new Song("Scarlet's Remains",198.73914,"gothic metal","Spin");
        new Song("The Suicide Machines",95.68608,"ska punk","Burning In The Aftermath");
        new Song("The Rolling Stones",271.49016,"blues","Angie (1993 Digital Remaster)");
        new Song("Roberto Torres",226.66404,"salsa","Sabor Guajiro");
        new Song("Loudon Wainwright III",190.48444,"modern rock","Human Cannonball");
        new Song("R.L. Burnside",277.78567,"delta blues","Glory Be");
        new Song("Stevie Ray Vaughan",248.78975,"texas blues","Crossfire");
        new Song("John Hammond",195.3171,"blues","I Can't Be Satisfied");
        new Song("Casiotone For The Painfully Alone",175.72526,"trip hop","Nashville Parthenon");
        new Song("Ec8or",217.23383,"hardcore techno","Cocain Ducks");
        new Song("The New York Dolls",344.05832,"glam rock","Human Being");
        new Song("Eliane Elias",251.42812,"brazilian jazz","The More I See You");
        new Song("Lost Boyz",269.7922,"gangster rap","Certain Things We Do");
        new Song("The Germs",206.05342,"rock","Forming");
        new Song("Yamandu Costa",190.04036,"brazilian jazz","MafuA!");
        new Song("Chris Rea",241.162,"soft rock","Driving Home For Christmas");
        new Song("Perrey And Kingsley",122.64444,"easy listening","Spooks In Space");
        new Song("Eurythmics",207.0722,"dance rock","Tous Les GarASSons Et Les Filles");
        new Song("Francis Dunnery",300.79955,"singer-songwriter","Too Much Saturn");
        new Song("John Cale",228.46649,"experimental rock","Movement 4 [from Kiss] (Album Version)");
        new Song("Suzanne Ciani",239.59465,"meditation","Stream");
        new Song("Vickie Winans",228.93669,"ccm","Make Me Over");
        new Song("The Berzerker",165.61587,"speedcore","Deform (live)");
        new Song("Kings Of Leon",187.92444,"southern rock","Wicker Chair");
        new Song("Edith Lefel",276.50567,"zouk","An ti chans'");
        new Song("Taras",200.25424,"trance","I Will Love Again (JJ's Club Radio)");
        new Song("NOFX",144.50893,"punk","Stickin In My Eye");
        new Song("Murskahumppa",285.17832,"suomi rock","Ota kiinni");
        new Song("Soda Stereo",246.69995,"rock","Entre CanAbales");
        new Song("Bruce Rowland",84.03546,"easy listening","Rosemary Recalls");
        new Song("Xcultures",273.52771,"gabba","Sudanese Dance");
        new Song("White Heart",298.84036,"ccm","Where The Thunder Roars (Tales Of Wonder Album Version)");
        new Song("Heavy D / McGruff",161.38404,"pop rap","Wanna Be A Player");
        new Song("Van Halen",209.29261,"heavy metal","Panama (Remastered Album Version)");
        new Song("Black Eyed Peas",229.61587,"hip hop","Let's Get It Started");
        new Song("Nine Inch Nails",426.89261,"industrial metal","Metal");
        new Song("Nick Cave & The Bad Seeds",269.26975,"rock","She Fell Away (2009 Digital Remaster)");
        new Song("Nadine Renee",249.41669,"freestyle","Next Time");
        new Song("Lesley Gore",136.48934,"brill building pop","It's My Party");
        new Song("Smartbomb",233.27302,"melodic hardcore","Complicate It");
        new Song("Suburbs",187.24526,"british pop","Monde De Fou");
        new Song("Emperor",72.61995,"heavy metal","Opus a Satana (Part 2)");
        new Song("Julien Clerc",272.63955,"chanson","This Melody (Live)");
        new Song("Glen Campbell",142.75873,"country rock","I'm Gone This Time");
        new Song("T.G. Sheppard",194.11546,"country rock","You Feel Good All Over");
        new Song("Slim Whitman",195.91791,"folk-pop","Indian Love Call");
        new Song("Savage Garden",118.33424,"easy listening","You Can Still Be Free");
        new Song("Queens Of The Stone Age",288.41751,"stoner metal","I Never Came");
        new Song("Hank Penny & The Lincoln Penny Orchestra",123.21914,"western swing","Dixie");
        new Song("Inspiral Carpets",283.76771,"indie rock","Commercial Reign");
        new Song("Borialis",239.3073,"rap rock","Hourglass");
        new Song("The Dirty Skirts",206.75873,"indie rock","Wake");
        new Song("Flor Silvestre",134.81751,"ranchera","Caricia Y Herida");
        new Song("BA(c)zu",285.64853,"chanson","Le tortillard");
        new Song("Redman",124.18567,"hip hop","WKYA (drop)");
        new Song("Solistiyhtye Suomi",134.08608,"german pop","TerA$?slintu");
        new Song("Eddie Cantor",155.61098,"easy listening","Now's The Time To Fall In Love");
        new Song("Schizoid",275.40853,"breakcore","Grim Prospects (Gross Prospects - Bad Trip Remix)");
        new Song("Kai Winding",223.4771,"hard bop","Mangos");
        new Song("Sonny Simmons",443.24526,"free jazz","A Distant Voice");
        new Song("Mira",177.81506,"shoegaze","Openbare Weg");
        new Song("Citizen Kaned",385.33179,"chill-out","President Johnson");
        new Song("The Brooklyn Tabernacle Choir",324.44036,"gospel","Lead Me Lord");
        new Song("Ellen McIlwaine",275.12118,"blues-rock","Spontanous Combustion");
        new Song("Vince Guaraldi / Bola Sete",294.66077,"latin jazz","Choro");
        new Song("Maurice Chevalier",193.20118,"chanson","Ma Louise");
        new Song("Carl Cox Vs Yousef",357.82485,"tech house","I Want You (Forever)");
        new Song("Organized Konfusion",198.3473,"hip hop","Hate");
        new Song("Martina McBride",261.95546,"country","I Can't Stop Loving You");
        new Song("Horace Andy",176.27383,"roots reggae","Thank You Lord");
        new Song("Nazz",220.89098,"freakbeat","How Can You Call That Beautiful (Stewkey Vocal)");
        new Song("Tyrone Davis",235.91138,"chicago soul","Cheatin' In The Next Room");
        new Song("Hot Tuna",239.59465,"blues-rock","Candy Man");
        new Song("Richard Burton",171.49342,"jazz fusion","I See The Boys Of Summer");
        new Song("Rory Block",266.05669,"delta blues","Three Is a Crowd");
        new Song("Boyz II Men",329.27302,"new jack swing","On Bended Knee");
        new Song("Howard Armstrong",198.922,"piedmont blues","My Four Reasons");
        new Song("Donny Hathaway",283.21914,"jazz funk","Little Girl (LP Version)");
        new Song("Miguel Gallardo",238.68036,"male vocalist","Eternamente Amame");
        new Song("Les Ogres De Barback",254.06649,"chanson","Niev nietch nievitch");
        new Song("DJ X-Change featuring DJ Joey A",184.31955,"ghetto tech","Come Over");
        new Song("Morel",311.40526,"dance pop","Blue Taxi");
        new Song("Tony Joe White",162.53342,"country rock","I Want Love (Tween You & Me) (Album Version)");
        new Song("Wolfmother",212.37506,"stoner metal","White Feather");
        new Song("The Roches",338.33751,"singer-songwriter","Christlike Roche");
        new Song("Bob Margolin",126.51057,"blues-rock","You Rascal You");
        new Song("Thomas Battenstein",205.58322,"guitar","Sympathy");
        new Song("Jupiter Rising",193.4624,"pop rap","They Say (Album)");
        new Song("Dharma Bums",127.4771,"progressive house","Simon's Folly");
        new Song("Saafir",234.762,"hip hop","Crawl Before You Ball (Album Version)");
        new Song("The Verve Pipe",292.8322,"post-grunge","Medicate Myself");
        new Song("Bob Neuwirth",241.10975,"singer-songwriter","Biding Her Time");
        new Song("Marvin Sapp",270.68036,"gospel","More And More  (LP Version)");
        new Song("James Hunter",188.73424,"blue-eyed soul","Cowboy Ways");
        new Song("Nelson Ned",211.80036,"latin jazz","Brasas Vivas");
        new Song("Mish Mash",254.32771,"vocal house","Kolomeyke");
        new Song("Cama",210.36363,"los angeles","In This Life");
        new Song("Maxi Priest",301.81832,"lovers rock","Groovin' In The Midnight");
        new Song("Porcupine Tree",416.80934,"experimental rock","Waiting");
        new Song("Ragheb Alama",413.36118,"arabesque","A'chek Ouyounik (2009 Digital Remaster)");
        new Song("Foo Fighters",117.002,"grunge","Hell");
        new Song("Shakira Featuring Wyclef Jean",217.36444,"dance pop","Hips Don't Lie (featuring Wyclef Jean)");
        new Song("The Avengers",122.72281,"rock","Juoksuhauta-twist (ElA$?mA$? juoksuhaudoissa)");
        new Song("Robben Ford",203.98975,"blues-rock","I Got Over It (Album Version)");
        new Song("Brazilian Tropical Orchestra",192.44363,"bossa nova","One Less Bell To Answer");
        new Song("Gil Semedo",285.36118,"zouk","Festa");
        new Song("Soda Stereo",225.12281,"rock","Te Hacen Falta Vitaminas");
        new Song("Xmilk",123.66322,"thrash core","Sense And Trick");
        new Song("Dolce; Oscar G.",525.16526,"folk-pop","Fire (Oscar G Space Vocal Mix)");
        new Song("Britt Nicole",204.06812,"ccm","Hanging On (Medium Key Performance Track Without Background Vocals)");
        new Song("Schizoid",166.00771,"breakcore","Grim Prospects (Version 2 Remix)");
        new Song("Toni Braxton Featuring Shaggy",219.01016,"dance pop","Christmas In Jamaica");
        new Song("Perrey And Kingsley",127.9473,"easy listening","Gossippo Perpetuo");
        new Song("Sven Tasnadi",570.90567,"tech house",",2190 Dias Contigo");
        new Song("Eddie",230.00771,"frevo","No Control");
        new Song("Enthroned",240.74404,"black metal","The Vitalized Shell");
        new Song("Suzanne Ciani",192.20853,"meditation","Mozart");
        new Song("Milan Band",152.0322,"serialism","Ciao Milan");
        new Song("Johnny Osbourne",215.30077,"roots reggae","Lend Me Your Chopper");
        new Song("Dolly Parton",155.21914,"bluegrass","Letter To Heaven");
        new Song("Rance Allen Group",207.12444,"jazz funk","Heaven is Where The Heart Is");
        new Song("Pearl Jam",428.56444,"grunge","Inside Job");
        new Song("Natalie Cole",185.7824,"vocal jazz","Take A Look  (LP Version)");
        new Song("Mastodon",654.28853,"alternative metal","The Czar: Usurper/Escape/Martyr/Spiral (Album Version)");
        new Song("Kiril Valeri",306.72934,"flamenco","Bulgarian Dream");
        new Song("Word",229.51138,"blues-rock","Amalgama");
        new Song("DJ Quik",205.58322,"gangster rap","Born and Raised In Compton");
        new Song("Hank Locklin",127.05914,"honky tonk","We're Gonna Go Fishin'");
        new Song("BT",44.35546,"electronica","Robbers Kill Cop");
        new Song("2-4 Grooves feat. Reki D.",203.83302,"vocal house","Relax");
        new Song("The Jordanaires",176.50893,"country gospel","Sweet By And By");
        new Song("Descendents",140.66893,"hardcore punk","Orgofart");
        new Song("L.A. Guns",201.09016,"heavy metal","Bitch Is Back");
        new Song("Bare Jr.",254.79791,"post-grunge","Naked Albino");
        new Song("Shelley Fabares",143.0722,"brill building pop","Johnny Loves Me (LP Version)");
        new Song("Norrie Paramor",163.49995,"easy listening","Dearly Beloved");
        new Song("Gary Hobbs",289.64526,"tejano","The Look Of Love");
        new Song("Diesel Boy",124.15955,"pop rock","Cooler Than You");
        new Song("Angelo Badalamenti",167.3922,"chill-out","Taryns Deepest Fear");
        new Song("Cradle Of Filth",321.35791,"sympho black metal","Summer Dying Fast");
        new Song("Jim Chappell",263.94077,"chamber jazz","Still");
        new Song("Ladybug",341.36771,"dancehall","Snapshot");
        new Song("Bandido",333.13914,"hard house","End Of The Road (Head Horny's Remix)");
        new Song("Brixx",349.12608,"rap",",7 Miles");
        new Song("Nine Inch Nails",168.56771,"industrial metal","The Frail");
        new Song("Susana Seivane",350.71955,"gaita","Para Milladoiro");
        new Song("Leland Martin",175.62077,"honky tonk","Stone Cold Fingers (Bonus Track)");
        new Song("Test Icicles",190.24934,"grime","Snowball");
        new Song("Heaven 17,",255.16363,"new romantic","(We Don't Need This) Fascist Groove Thang");
        new Song("React",120.2673,"happy hardcore","Drunk Alone");
        new Song("Sven Tasnadi",557.26975,"tech house","Charisma");
        new Song("Mance Lipscomb",187.53261,"texas blues","Going Down Slow");
        new Song("Scott Wesley Brown",295.60118,"modern rock","All Rise");
        new Song("FlA!vio JosA(c)",252.02893,"brazil","Jogo Limpo");
        new Song("Moss",329.35138,"future jazz","Silent Hill");
        new Song("Pery Ribeiro",180.00934,"bossa nova","Our Love Is Here To Stay");
        new Song("Soular",244.45342,"breakbeat","Everything Changes");
        new Song("Dimmu Borgir",282.53995,"black metal","Master Of Disharmony");
        new Song("Public Image Ltd",388.28363,"dance rock","(This Is Not A) Love Song (Live)");
        new Song("Gary Moore",345.93914,"blues-rock","What Are We Here For");
        new Song("Pascal Sangla",243.1473,"french pop","Une petite pause");
        new Song("The B-52's",261.74649,"dance rock","Wig");
        new Song("Dakis",172.25098,"greek","Perasmena Mesanihta");
        new Song("Sex Pistols",216.60689,"punk","God Save the Queen (Live)");
        new Song("Chris Brown",363.59791,"r&b","Forever");
        new Song("Deekline & Wizard",271.77751,"breakbeat","Sun Is Shining");
        new Song("Daniela DessA!",330.65751,"opera","New Age");
        new Song("Hem",133.27628,"folk-pop","Have Yourself A Merry Little Christmas");
        new Song("Lily Allen",264.69832,"ska","U Killed It");
        new Song("Pentangle",228.51873,"british invasion","Rain And Snow");
        new Song("DJ Dips",240.3522,"turnablism","Gerra De De");
        new Song("Ana Bekuta",145.57995,"pop folk","Kako mi je pitas sad");
        new Song("Jason Miles",235.80689,"jazz fusion","Voices On The Corner");
        new Song("Busdriver",192.1824,"alternative hip hop","(Bloody Paw On The) Kill Floor");
        new Song("Byther Smith",418.87302,"chicago blues","I Wish My Mother Was Here");
        new Song("Bebo & Cigala",198.26893,"latin jazz","Inolvidable");
        new Song("Bizarre Inc",420.10077,"breakbeat","Miracle");
        new Song("Bongzilla",397.26975,"stoner metal","Witch Weed (Live)");
        new Song("The Gone Jackals",229.79873,"blues-rock","Not Buried Deep Enough");
        new Song("The Willis Brothers",150.64771,"western swing","Give Me 40 Acres (To Turn This Rig Around)");
        new Song("Laurindo Almeida / Carlos Barbosa-Lima / Charlie Byrd",286.14485,"latin jazz","Ernesto Nazareth");
        new Song("S.U.P",384.70485,"doom metal","The Cube (Live)");
        new Song("Boogie Pimps",415.03302,"hard house","Get Back Down");
        new Song("Brian Keane",133.53751,"world beat","Battle Of The Rosebud / Cries");
        new Song("Aberdeen",266.70975,"twee pop","Beyond the Light");
        new Song("The Killers",284.3424,"rock","Spaceman");
        new Song("Gloriana",179.06893,"teen pop","Pulecenella 'e mA2,");
        new Song("Butterfly Temple",100.5971,"doom metal","Iskorosten' (instr.)");
        new Song("Grant Geissman",320.60036,"smooth jazz","Big Stax/High Volts (Album Version)");
        new Song("20/20,",302.36689,"power pop","It Goes On");
        new Song("JosA(c) Augusto",284.70812,"latin pop","Pecado De Amor");
        new Song("Orbital",327.8624,"techno","Illuminate");
        new Song("Bone Thugs-N-Harmony / Akon",286.30159,"gangster rap","Never Forget Me");
        new Song("Moonsorrow",356.49261,"viking metal","Ukkosenjumalan poika");
        new Song("N.W.A.",168.75057,"gangster rap","A B***** Is A B***** (Edited)");
        new Song("Rage Against The Machine",201.56036,"rap metal","Kick Out The Jams");
        new Song("Jazz Gillum",185.67791,"chicago blues","Me And My Buddy");
        new Song("Rise Against",218.8273,"hardcore punk","Amber Changing");
        new Song("Ultraviolence",303.04608,"gabba","Murder Academy");
        new Song("Korn",224.522,"rap metal","Hey Daddy");
        new Song("Sir Neville Marriner",315.27138,"requiem",",4 Sea Interludes Op. 33a: Storm");
        new Song("Agnes",275.06893,"europop","I Need You Now");
        new Song("James Horner",191.81669,"rock","Atmosphere Station");
        new Song("Tantric",177.24036,"post-grunge","Walk Away");
        new Song("Mastodon",233.58649,"alternative metal","Shadows That Move");
        new Song("Xcultures",38.3473,"gabba","Smile");
        new Song("The Irish Tenors",100.85832,"irish folk","Mountains Of Mourne");
        new Song("U2,",485.19791,"dance rock","Kite Live from Sydney");
        new Song("Little Joe",239.01995,"soul jazz","Loco (Crazy)");
        new Song("Korn",288.49587,"rap metal","Ever Be");
        new Song("Blind Blake & The Royal Victoria Hotel Calypsos",151.53587,"country blues","Oh Look Misery");
        new Song("Percy Faith",160.28689,"instrumental pop","Yesterdays");
        new Song("Extreme",181.55057,"funk metal","Teacher's Pet");
        new Song("Alexandre Desplat",70.26893,"soundtrack","Palmer enquAate");
        new Song("Prozak",173.24363,"rap","Go To Hell");
        new Song("Jerry Butler",155.74159,"chicago soul","Moon River - Original");
        new Song("Yvette Horner",148.03546,"chanson","La Plus Bath Des Javas");
        new Song("Delta 9,",94.06649,"gabba","Infidel");
        new Song("Placebo",241.52771,"british pop","English Summer Rain");
        new Song("Tam Tam Go!",226.82077,"pop rock","Spanish Shuffle (Album Version)");
        new Song("Gertrudis",106.52689,"big beat","Intro");
        new Song("Warrior King",224.28689,"roots reggae","Empress So Divine");
        new Song("Soda Stereo",340.29669,"rock","Terapia De Amor Intensiva");
        new Song("LORE",216.55465,"trip hop","Haunting");
        new Song("Soul Asylum",279.2224,"hard rock","Lies Of Hate");
        new Song("Carl Doy with NZSO",158.56281,"progressive house","The First Noel");
        new Song("Horace Andy",234.44853,"roots reggae","Musical Episode");
        new Song("Jimmy Wakely",155.95057,"classic country","Beautiful Brown eyes");
        new Song("The Nightraver & The Magican",233.53424,"gabba","Drop the Bass");
        new Song("Rah Digga (Featuring Outsidaz)",256.80934,"hip hop","The Last Word (Amended Version)");
        new Song("RUN-DMC",234.65751,"hip hop","Hard Times");
        new Song("Bert Kaempfert And His Orchestra",163.76118,"orchestra","Just As Much As Ever");
        new Song("Hank Locklin",159.03302,"honky tonk","Filipino Baby");
        new Song("Lady May",214.04689,"hip hop","The Boss");
        new Song("Nightwish",301.06077,"sympho black metal","Escapist");
        new Song("Angelo Badalamenti",109.37424,"chill-out","Jeffrey's Dark Side");
        new Song("Frank Chacksfield",151.82322,"orchestra","Someone to Watch Over Me");
        new Song("Cesar Camargo Mariano/Helio Delmiro",287.11138,"latin jazz","Milagre Dos Peixes/ Musica Incidental: Cais/ Music Incidental: San Vicente");
        new Song("Buzzhorn",239.98649,"post-grunge","Pinned To The Ground (album version)");
        new Song("Silverstein",229.642,"post-hardcore","Always And Never (Album Version)");
        new Song("!!!",143.98649,"dance-punk","Myth Takes");
        new Song("The Secret Life of Teenage Girls",153.20771,"grindcore","Carpe PM");
        new Song("The Notorious B.I.G.",316.65587,"gangster rap","Who Shot Ya (Amended Album Version)");
        new Song("Led Zeppelin",182.09914,"blues-rock","Poor Tom (Album Version)");
        new Song("Sandi Thom",205.21751,"british pop","Wounded Hearts");
        new Song("Carl Belew",131.05587,"rockabilly","Love's Been Good To Me");
        new Song("The Field Mice",316.73424,"twee pop","When Morning Comes To Town");
        new Song("Billy Higgins_ Bob Berg_ Cedar Walton_ Tony Dumas",431.64689,"hard bop","Estate");
        new Song("Catherine Howe",183.37914,"chill-out","Freedom Enough (From Silent Mother Nature)");
        new Song("Malkit Singh",324.51873,"broken beat","Hai Shava");
        new Song("Rodney O & Joe Cooley",172.01587,"miami bass","Nutty Block");
        new Song("Dean Martin",165.66812,"vocal","Until You Love Someone");
        new Song("Strata",377.67791,"post-grunge","Part One From Triomusic");
        new Song("James Darren",145.00526,"brill building pop","Hello Young Lovers (LP Version)");
        new Song("Till West & DJ Delicious",153.28608,"funky house","Same Man");
        new Song("Carlos NuA+-ez",215.35302,"flamenco","Quiero Ir Ao Mar");
        new Song("Igor Stravinsky",156.70812,"ballet","The Owl and the Pussy-cat");
        new Song("Gene Clark",168.38485,"country rock","Set You Free This Time");
        new Song("Maysa",150.25587,"brazilian pop music","Bloco Da Solidao (1996 Digital Remaster)");
        new Song("The Shirelles",159.76444,"doo-wop","Will You Love Me Tomorrow");
        new Song("The American Boychoir",230.26893,"j pop","Stille nacht_ heilige nacht");
        new Song("JDS",465.60608,"happy hardcore","Nine Ways");
        new Song("Panic At The Disco",247.77098,"pop punk","Northern Downpour (Album Version)");
        new Song("Jan Howard",165.98159,"classic country","Bad Seed");
        new Song("Abraham Laboriel",368.16934,"jazz","Exchange");
        new Song("MichA le Arnaud",176.27383,"chanson","Marie D'Aquitaine");
        new Song("Sticky Fingaz",266.4224,"hip hop","Oh My God");
        new Song("Dame Joan Sutherland / New Philharmonia Orchestra / Richard Bonynge",111.0722,"bel canto","Joy To The World");
        new Song("The Jeff Healey Band",313.7824,"blues-rock","Hoochie Coochie Man");
        new Song("Angela Dimitriou",265.37751,"pop folk","Ftei O Erotas");
        new Song("Danny Wilson",167.20934,"british pop","The Second Summer Of Love");
        new Song("Lionel Rogg",240.61342,"early music","Prelude And Fugue In C Major BWV 531 : Fugue");
        new Song("Java",356.41424,"musette","Don't Phunk With My Heart");
        new Song("SWAMI featuring Asuivre",260.28363,"downtempo","Give It What U Got");
        new Song("The Black Velvet Band",256.39138,"irish folk","Dancing To A Standstill");
        new Song("Lisa Lynne",316.49914,"chill-out","Isla del Luna");
        new Song("Pe'z",252.57751,"argentine rock","Spirit");
        new Song("Shawn Colvin",224.60036,"country rock","Another Long One");
        new Song("Stephy Tang",214.12526,"cantonese pop","Leng Jing");
        new Song("Casual",259.44771,"hip hop","OAKtown");
        new Song("Backstreet Boys",236.25098,"teen pop","Larger Than Life");
        new Song("Tiny Tim",43.36281,"cabaret","I Hold Your Hand In Mine [Live At Royal Albert Hall]");
        new Song("Kenny G featuring Daryl Hall",236.93016,"instrumental pop","Baby Come To Me");
        new Song("Christos Dantis",243.82649,"pop rock","Den Pai Alo");
        new Song("David Martin",241.47546,"screamo","It Wont Be Christmas");
        new Song("John Davis",183.17016,"jazz fusion","Knocked Out Of The Park");
        new Song("Trafik",424.12363,"progressive house","Salt In NYC");
        new Song("Nick Ingman;Gavyn Wright",111.62077,"jazz funk","Wessex Loses a Bride");
        new Song("Eddie Calvert",138.63138,"cool jazz","Erica (2005 Digital Remaster)");
        new Song("Glad",270.602,"ccm","Blessed Assurance");
        new Song("Steel Rain",173.19138,"country rock","Loaded Like A Gun");
        new Song("Los Manolos",218.38322,"flamenco","Rumba De Barcelona");
        new Song("Gloriana",153.33832,"teen pop","Clementina SantafA");
        new Song("Bombay Rockers",230.71302,"bhangra","Wild Rose (Back 2 Basics Mix)");
        new Song("Jinx",407.37914,"breakbeat","Kutt Free (DJ Volume Remix)");
        new Song("Chase & Status",337.68444,"breakbeat","Ten Tonne");
        new Song("Tom Petty",236.17261,"heartland rock","A Higher Place (Album Version)");
        new Song("Montserrat CaballA(c);Placido Domingo;Vicente Sardinero;Judith Blegen;Sherrill Milnes;Georg Solti",511.16363,"symphonic rock","Sono andati? Fingevo di dormire");
        new Song("Pucho & His Latin Soul Brothers",338.23302,"latin jazz","Got My Mojo Workin");
        new Song("Soul Mekanik",45.66159,"tech house","Get Your Head Stuck On Your Neck");
        new Song("Mitch Ryder",207.43791,"blues-rock","Jenny Take a Ride");
        new Song("Blingtones",29.54404,"turnablism","Sonnerie lalaleulA(c) hi houuu");
        new Song("Luna Orbit Project",335.51628,"club","Midnight Star");
        new Song("Danilo Perez",197.19791,"latin jazz","Native Soul");
        new Song("Line Renaud",152.92036,"chanson","Der Kleine Dompfaff");
        new Song("King Curtis",326.00771,"instrumental rock","A Whiter Shade Of Pale (Live @ Fillmore West)");
        new Song("Sophie B. Hawkins",305.162,"ballad","The Ballad Of Sleeping Beauty");
        new Song("Lupe Fiasco",279.97995,"hip hop","Streets On Fire (Explicit Album Version)");
        new Song("Wilks",261.51138,"hip hop","Music is what we love");
        new Song("Marc Shaiman",149.86404,"soundtrack","City Slickers");
        new Song("40 Grit",75.67628,"nu metal","Intro");
        new Song("Gwen Stefani",290.55955,"rock","Harajuku Girls");
        new Song("Steve Morse",363.85914,"blues-rock","Prognosis");
        new Song("Bitter End",282.43546,"stoner metal","Living Hell");
        new Song("Ethel Merman",135.31383,"vaudeville","Small World");
        new Song("Leon Russell & New Grass Revival",221.30893,"blues-rock","Truck Driving Man/Down In The Caribbean");
        new Song("Story Of The Year",75.57179,"screamo","Swallow The Knife (Live) (Segue)");
        new Song("Natural Elements",338.1024,"hip hop","Mayday");
        new Song("Lisa Lynne",298.10893,"chill-out","Lake Of Dreams");
        new Song("Neil Sedaka",170.84036,"brill building pop","Because Of You");
        new Song("Maurice Larcange",215.37914,"chanson","Un Peu D'Amour Et D'AmitiA(c)");
        new Song("A Static Lullaby",213.49832,"post-hardcore","Rattlesnake!");
        new Song("John Wesley_ John Wesley",351.08526,"disco","Disappeared");
        new Song("Coph Nia",658.02404,"dark ambient","DoppelgA$?nger [Qliphothic Phantasmagoria]");
        new Song("Tabu feat. Mitzib",474.61832,"cumbia","Ain't No Love Ain't No Use (Love To Infinity Full Funk Mix)");
        new Song("Nights Like These",305.89342,"doom metal","Ghost Town Rituals (Album Version)");
        new Song("Oasis",301.92281,"british pop","Morning Glory");
        new Song("John Davis & Emma Doyle",135.52281,"jazz fusion","Rudolph The Red-Nosed Reindeer");
        new Song("Stew",179.9571,"cabaret","Tomorrow Gone");
        new Song("Jauida",269.76608,"male vocalist","I don't Want to Be Alone Tonight");
        new Song("Eddy Arnold",166.16444,"honky tonk","Just A Little Lovin' (Will Go A Long Way)");
        new Song("All Time Low",221.67465,"pop punk","Shameless");
        new Song("Brian Dullaghan",212.94975,"irish folk","And I Love You So");
        new Song("Richard Galliano",261.74649,"tango","L' Envers Du DA(c)cor");
        new Song("Regina Belle",307.33016,"vocal jazz","Quiet Time");
        new Song("Debbie Davies",225.67138,"blues-rock","Little Sister");
        new Song("STEVE CAMP",296.14975,"ccm","Song For Mom (LP Version)");
        new Song("Jay Tee & Baby Bash",203.67628,"hard house","All Over Me");
        new Song("The Stolen Minks",56.42404,"dance rock","I Hate You");
        new Song("Daath",230.86975,"technical death metal","From The Blind (LP Version)");
        new Song("Extasick",134.03383,"digital hardcore","Misanthrope");
        new Song("UFO",212.61016,"heavy metal","Chains Chains (Live In Hammersmith)");
        new Song("Avril - Remix By Ana Rago",188.39465,"trip hop","The Date (Remix By Ana Rago)");
        new Song("Pat Travers",152.99873,"blues-rock","As My Fire Flies");
        new Song("SNOWPATROL",233.03791,"indie rock","We Wish You A Merry Christmas");
        new Song("Die Fantastischen Vier",149.99465,"pop rap","BAPse");
        new Song("Jeanie Lambe & The Danny Moss Quartet",152.0322,"hip hop","Saturday Night Is The Loneliest Night In The Week");
        new Song("Nelson Ned",200.48934,"latin jazz","A Mi No Me Importa");
        new Song("Yung Joc",193.64526,"gangster rap","BYOB (Explicit Album Version)");
        new Song("Philippe Sarde",158.82404,"smooth jazz","Le PresbytAre n'a rien perdu de son Charme");
        new Song("Orquesta AragA3n",173.68771,"charanga","Ven Morena");
        new Song("Jason Miles",269.40036,"jazz fusion","Brighton by the Sea");
        new Song("State of Chaos",176.90077,"tech house","CHAOS INTRO");
        new Song("Dropkick Murphys",196.72771,"celtic punk","Bloody Pig Pile (Live)");
        new Song("Taint",281.46893,"power electronics","Hex Breaker");
        new Song("VHS Or Beta",224.20853,"disco","The Melting Moon (Edit)");
        new Song("Leonard Kwan",170.31791,"slack key guitar","Hawaiian Chimes");
        new Song("True Believers",361.53424,"melodic hardcore","Turn Around");
        new Song("Les Hurlements D'leo",182.04689,"folk rock","L'accordA(c)oniste");
        new Song("Charanga Forever",367.43791,"salsa","Tumba Tumba");
        new Song("Zuzu Bollin",175.90812,"r&b","Why don't you eat where you slept last night ?");
        new Song("Bullet For My Valentine",215.53587,"alternative metal","Suffocating Under Words Of Sorrow (What Can I Do)");
        new Song("The Hit Factory",234.70975,"free music","I'm Moving On");
        new Song("Terry Snyder",340.11383,"space age pop","Deep Night/Softly As In A Morning Sunrise (Medley)");
        new Song("Marcus Miller",280.13669,"jazz funk","Let Me Show You [I Just Want To Make You Smile]");
        new Song("Beatnuts",170.52689,"grime","Monster For Music");
        new Song("Ayo",212.71465,"neo soul","Complain");
        new Song("Kid Sister",277.2371,"hip house","Daydreaming [Jakwob Remix]");
        new Song("Mons Leidvin Takle",120.92036,"lullaby","Dansende Foran Speilet");
        new Song("Public Image Ltd",492.30322,"dance rock","Ease");
        new Song("Rise Against",260.8322,"hardcore punk","Everchanging");
        new Song("Sizzla",203.96363,"dancehall","Too much informa");
        new Song("Richard Galliano",309.65506,"tango","L'insidieuse (Live)");
        new Song("Helen Love",81.97179,"power pop","So Hot");
        new Song("David Mingyue Liang",757.99465,"chinese music","Youlan_ Lonely Orchid (solo guqin)");
        new Song("Pursuit Of Happiness",196.49261,"power pop","Forbidden Fruit");
        new Song("Bobby Hutcherson",352.57424,"latin jazz","Recorda-Me");
        new Song("Gregory Isaacs",221.83138,"lovers rock","Lady Of Your Calibre");
        new Song("The Pharcyde",11.59791,"rap","Italian For Goodbye (skit)");
        new Song("Azis",281.88689,"pop folk","Anti Geroi");
        new Song("Amy Winehouse",256.10404,"vocal jazz","Stronger Than Me");
        new Song("George Lopez",345.23383,"california","Only For The Young");
        new Song("Les Hou-Lops",122.69669,"freakbeat","T'as 16 ans demain");
        new Song("The Cosmosamatics",338.36363,"free jazz","Serene");
        new Song("Jackie Edwards",256.62649,"rock steady","So Jah Seh");
        new Song("Michael Card",182.72608,"ccm","Joy In The Journey (The Final Word Album Version)");
        new Song("Richard Galliano",197.17179,"tango","Chorinho Pra Ele (Live)");
        new Song("Ensiferum",291.02975,"power metal","Warrior's Quest");
        new Song("Leila Chicot",293.27628,"zouk","Medley LeA-la Chico");
        new Song("The Pharcyde / Big Boy / Schmooche Cat / Randy Mack",334.78485,"rap","The Hustle");
        new Song("Erkki Junkkarinen",215.82322,"humppa","Rakkauden satu - Histoire d'un Amour -");
        new Song("A Static Lullaby",237.42649,"post-hardcore","God Bless You (Goddamn it)");
        new Song("Scar Symmetry",271.5424,"death metal","The Illusionist");
        new Song("Oztara",207.51628,"musette","La Route Est Belle");
        new Song("Sonia Dersion",269.87057,"zouklove","Urgence");
        new Song("Christina Aguilera",266.73587,"dance pop","Pero Me Acuerdo De TA");
        new Song("Headhunter",312.76363,"dubstep","Trapped In Reality");
        new Song("Eighteen Visions",172.19873,"alternative metal","Our Darkest Days");
        new Song("Baby Huey & The Baby Sitters",288.36526,"funk","California Dreamin' (LP Version)");
        new Song("Elmore James",191.13751,"chicago blues","Dumb Woman Blues");
        new Song("Rising Lion",280.45016,"roots reggae","Letting You Back In");
        new Song("George Harrison",359.73179,"classic rock","Hear Me Lord (2001 Digital Remaster)");
        new Song("Weezer",180.97587,"pop rock","Don't Let Go");
        new Song("Rodney O & Joe Cooley",217.41669,"miami bass","U Don't Hear Me Tho' (Street Mix)");
        new Song("Boots Randolph",150.20363,"instrumental rock","Lonely Street");
        new Song("Jackson United",204.93016,"surf music","Undertow");
        new Song("The Cosmosamatics",515.97016,"free jazz",",12 Seasons of Love");
        new Song("Bobbie Gentry",177.57995,"country blues","Courtyard");
        new Song("Creedence Clearwater Revived",257.59302,"country rock","Have You Ever Seen The Rain");
        new Song("The Johnny Otis Orchestra",182.15138,"jump blues","Cry Baby");
        new Song("B.A.D.",102.03383,"dance rock","Interlude");
        new Song("Luar Na Lubre",251.81995,"freestyle","Terra");
        new Song("Circular",59.89832,"chill-out","Mother");
        new Song("Fruko Y Sus Tesos",261.90322,"salsa","A La Memoria Del Muerto");
        new Song("The Bucketheads",365.71383,"vocal house","Sayin' Dope");
        new Song("The Police",216.42404,"new wave","When The World Is Running Down_ You Make The Best Of What's Still Around");
        new Song("Kinky",101.14567,"alternative dance","My Bonnie Lies Over the Ocean");
        new Song("The Real Kids",222.11873,"power pop","Now You Know");
        new Song("Eddie Boyd",203.36281,"chicago blues","I'm Sitting Here Waiting");
        new Song("Tha Chamba",281.75628,"rap","Korrupted - Remix");
        new Song("Jack Orsen & Taktlo$$",200.51546,"hip hop","Sex Objekt");
        new Song("Olov Johansson_ Catriona Mckay",469.68118,"world music","Rain / Ekoln");
        new Song("Shriekback",113.60608,"alternative dance","Reason With The Beast");
        new Song("Hatebreed",136.95955,"hardcore punk","As Diehard As They Come (Album Version)");
        new Song("John Frizzell",133.19791,"soundtrack","No Unexpected Guests");
        new Song("Sister Hazel",195.36934,"post-grunge","Walls And Cannonballs (Album)");
        new Song("J.J. Cale",202.94485,"blues-rock","Trouble In The City");
        new Song("Precious Bryant",193.72363,"blues","Dark Angel");
        new Song("Kings Of Leon",466.65098,"southern rock","Knocked Up");
        new Song("Selena",388.51873,"tejano","Ven Conmigo/Perdoname (Live)");
        new Song("Brooke Valentine",261.53751,"crunk","Taste Of Dis (Explicit Version)");
        new Song("Krystof",262.55628,"soft rock","Prvni vesela");
        new Song("Claire Hamill",205.42649,"new age","If You'd Only Talk To Me (Bonus Track)");
        new Song("Los Originales De San Juan",263.6273,"mariachi","Librado Maldonado");
        new Song("Black Flag",1030.19057,"hardcore punk","Crass Commercialism");
        new Song("Barbarito Diez",183.43138,"charanga","Flores Negras");
        new Song("Aaron Watson",217.39057,"honky tonk","Rollercoaster Ride");
        new Song("Mary Black",293.92934,"country rock","Turning Away");
        new Song("Satan's Host",332.7473,"heavy metal","Metal from Hell...22nd Century");
        new Song("The Impressions",159.29424,"chicago soul","The Girl I Find (LP Version)");
        new Song("Owl City",187.6371,"synthpop","Panda Bear");
        new Song("Bobby Bland",181.49832,"soul blues","Drifting From Town To Town");
        new Song("Headliners",169.56036,"hard house","Negativ Song");
        new Song("Jane Winther",145.68444,"meditation","The Lords Prayer");
        new Song("The Rascals",223.89506,"blue-eyed soul","Nubia (LP Version)");
        new Song("Blind Blake",186.90567,"country blues","Blake's Worried Blues");
        new Song("Emilia",174.81098,"europop","You're My World");
        new Song("CA3mplices",307.56526,"pop rock","Ojos Gitanos");
        new Song("Emilio",165.22404,"tejano","Mira Nina");
        new Song("Nana Caymmi",216.86812,"brazilian pop music","Solamente Una Vez");
        new Song("Kasia Stankiewicz",304.06485,"chill-out","Zolte Slonie");
        new Song("Turisas",146.59873,"viking metal","Sahti Waari");
        new Song("ChA(c)co Feliciano And Joe King",273.65832,"salsa","Nina Nina");
        new Song("Cache Cache",245.49832,"big beat","Only Do for Love");
        new Song("David Hudson",320.91383,"pop rock","Arrival");
        new Song("David Summers",321.33179,"pop","Las Murallas De JericA3,");
        new Song("Rummage",178.12853,"polka","Megatrend");
        new Song("Adr Lavey",194.45506,"gangster rap","In The Name of the Father");
        new Song("Bill Boyd's Cowboy Ramblers",203.75465,"western swing","I Can't Tame Wild Women");
        new Song("Canis Dirus",722.20689,"black metal","A Somber Wind from a Distant Shore (Album)");
        new Song("Vickie Winans",358.71302,"ccm","Little Timmy");
        new Song("Justin",149.49832,"future jazz","Erica");
        new Song("La Portuaria",132.25751,"disco","Marcando El Ritmo Al Caminar");
        new Song("Antonis Remos",140.64281,"pop folk","To Agalma");
        new Song("Percy Faith And His Orchestra",152.13669,"orchestra","Damisela Encantadora");
        new Song("Stars Like Fleas",264.51546,"glitch","You Are My Memoir");
        new Song("Gaetano Donizetti",206.68036,"bel canto","Donizetti: Roberto Devereux: L'ore trascorrono...");
        new Song("Shakira",148.1922,"dance pop","Pienso En Ti");
        new Song("Maysa",230.3473,"brazilian pop music","This Time I'll Be Sweeter");
        new Song("Little Freddie King",443.55873,"new orleans blues","Bus Station Blues (Live)");
        new Song("Ms. Dynamite",286.32771,"grime","Mr. Prime Minister");
        new Song("Andy Russell",156.94322,"world","I Love You And You Love Me");
        new Song("Blink-182,",225.12281,"power pop","A New Hope");
        new Song("Selena",329.58649,"tejano","Como La Flor (2005 Re-mastering) (Live)");
        new Song("Kali",349.83138,"hip hop","Ponto");
        new Song("Vickie Winans",287.03302,"ccm","Great Is Thy Faithfulness");
        new Song("John Brown",151.27465,"hard trance","Party In The Burbs");
        new Song("Abysmal Dawn",250.3571,"blackened death metal","Compulsory Resurrection");
        new Song("Chaotica",243.25179,"industrial rock","Lobotomy");
        new Song("Lara & The Gumbo Lickers",232.85506,"visual kei","The tears I cried");
        new Song("Elvin Bishop",254.56281,"blues-rock","Party Til The Cows Come Home");
        new Song("Gordon Jenkins",190.48444,"orchestra","Don't Cry_ Joe");
        new Song("1. Futurologischer Congress",107.49342,"kraut rock","La Excursion");
        new Song("Asleep At The Wheel",251.37587,"western swing","Big Balls And Cow Town");
        new Song("Neil Innes",190.74567,"pop rock","Lie Down And Be Counted (2007 Digital Remaster)");
        new Song("Marcus Miller",409.05098,"jazz funk","Your Amazing Grace (feat. Raul MidA3n)");
        new Song("Siouxsie",234.55302,"dark wave","Into A Swan");
        new Song("Claire Hamill",123.71546,"new age","To The Stars");
        new Song("Alan Silvestri",504.05832,"country rock","The Joes Mobilize");
        new Song("Sunnyland Slim",147.77424,"piano blues","I Got To Quit My Baby");
        new Song("Byther Smith",269.7922,"chicago blues","So Unhappy");
        new Song("Dusminguet",199.13098,"rumba","San Cristobal");
        new Song("Rudolph Valentino",184.73751,"ballad","Kashmiri Love Song");
        new Song("Sylvia Patricia",259.34322,"bossa nova","Marca de Amor NAPSo Sai");
        new Song("Zeromancer",362.31791,"industrial rock","Ammonite");
        new Song("Regina Belle",274.80771,"vocal jazz","If I Ruled The World");
        new Song("Two Man Advantage",50.83383,"thrash core","The Sweep");
        new Song("Green Day",340.79302,"alternative rock","Wake Me Up When September Ends (Live at Foxboro_ MA 9/3/05)");
        new Song("Ayo",229.25016,"neo soul","I Love You");
        new Song("Donny Hathaway",231.18322,"jazz funk","This Christmas (LP Version)");
        new Song("Chico",332.01587,"dirty south rap","Curvy Cola Bottle Body");
        new Song("KALIMBA",352.67873,"death core","VolcA!n");
        new Song("SKOLD vs. KMFDM",327.88853,"heavy metal","Alkohol");
        new Song("Architecture In Helsinki",345.75628,"twee pop","Heart it Races (Frank Tetaz Remix)");
        new Song("Wailing Souls",214.38649,"roots reggae","Very Well");
        new Song("Kitaro",81.50159,"chill-out","Village Attack/ The Arrest");
        new Song("Alice In Chains",256.522,"grunge","Lesson Learned");
        new Song("Bobby Darin",163.52608,"brill building pop","(I Heard That) Lonesome Whistle");
        new Song("Ini Kamoze",248.92036,"dancehall","Here Comes The Hotstepper");
        new Song("9th Wonder featuring Defcon_ Phonte",289.54077,"hip hop","Almost Genuine");
        new Song("The Real Kids",148.06159,"power pop","Can't Shake That Girl");
        new Song("Ill Nino",180.50567,"alternative metal","What You Deserve (Album Version)");
        new Song("De La Ghetto",280.45016,"reggaeton","Es dificil");
        new Song("Baroness",270.52363,"sludge metal","The Sweetest Curse");
        new Song("DMX / Eve / Jadakiss",265.22077,"hip hop","We're Back");
        new Song("Melt Banana",51.61751,"noise rock","Talk Like POP");
        new Song("M.I.K.E.",514.7424,"progressive trance","Fuego Caliente");
        new Song("Willie Rosario",281.41669,"salsa","Un Tipo Como Yo");
        new Song("Jude Taylor & His Burning Flames",260.46649,"zydeco","The Thrill Is Gone");
        new Song("Placebo",246.96118,"british pop","Slave To The Wage");
        new Song("Metallica",252.3424,"speed metal","Hit The Lights");
        new Song("Sui Generis",234.52689,"cumbia","Cancion Para Mi Muerte");
        new Song("The Red Telephone",273.55383,"power pop","Have You Seen Her");
        new Song("T-Bone",229.09342,"ccm","Don't Tell Me");
        new Song("Bill Douglas",331.07546,"chamber jazz","Karuna");
        new Song("DJ Spinn featuring Traxman",195.49995,"chicago house","Lil Mama Getdown");
        new Song("The Radio Dept.",256.02567,"shoegaze","Closing Scene");
        new Song("MAPtley CrA1/4e",254.01424,"heavy metal","Get It For Free");
        new Song("Shy FX & T Power",380.44689,"uk garage","Feelings");
        new Song("Becky Baeling",247.66649,"dance pop","If You Love Me");
        new Song("Keb' Mo'",190.56281,"blues","Still There For Me");
        new Song("UKW",266.762,"neue deutsche welle","Allein");
        new Song("THE CHIFFONS",166.922,"doo-wop","Doctor Of Hearts (Album Version)");
        new Song("S. Solis y Orquesta",182.20363,"musette","La Vida En Rosa");
        new Song("Commander Cody And His Lost Planet Airmen",188.70812,"country rock","Crying Time");
        new Song("Commissioned",342.83057,"ccm","You Can Always Come Home");
        new Song("Dee Clark",141.19138,"doo-wop","Little Bitty Pretty One");
        new Song("Cauterize",240.43057,"pop punk","Shooting Stars");
        new Song("Laurie Berkner",233.45587,"death core","The Cookie Bakers of the Night");
        new Song("DJ Slugo",199.20934,"bass music","Whip It");
        new Song("Joi",333.24363,"breakbeat","The Blessing");
        new Song("Simon & Garfunkel",194.35057,"folk-pop","Citizen Of The Planet");
        new Song("Beenie Man Featuring Wyclef And Redman",228.04853,"dancehall","Love Me Now (Rockwilder Remix) (Feat. Wyclef And Redman)");
        new Song("Robben Ford",298.37016,"blues-rock","Something For The Pain");
        new Song("Greater Vision",223.76444,"ccm","Everyone_ Everywhere_ Everytime");
        new Song("Anti-Flag",359.6273,"oi","This Is NOT a Crass Song");
        new Song("Joe Lynn Turner",247.7971,"hard rock","Soul Searcher");
        new Song("Rickie Lee Jones",221.12608,"folk rock","Skeletons (Live Acoustic Version)");
        new Song("Hysterie",389.642,"tech house","Imagination");
        new Song("Aesop Rock",234.52689,"underground rap","Flashflood");
        new Song("Bobby Vee",227.05587,"brill building pop","What To Do Crying Waiting Hoping Learning The Game");
        new Song("Alfredo GutiA(c)rrez",130.16771,"louisiana blues","El niA+-o de la calle");
        new Song("Shelby Lynne",290.97751,"country rock","Old Times Sake");
        new Song("Tora Tora",229.8771,"glam metal","Wasted Love");
        new Song("Franz Ferdinand",195.13424,"art rock","Eleanor Put Your Boots On");
        new Song("Hot Chip",181.02812,"dance rock","Ass Attack (Four Tet Remix)");
        new Song("Gal Costa",193.35791,"brazilian pop music","Canta Brasil");
        new Song("Kathy Mattea",44.64281,"bluegrass","Sally In the Garden");
        new Song("James Taylor",324.85832,"folk-pop","Steamroller Blues");
        new Song("Der Moderne Man",183.30077,"new wave","Heute");
        new Song("Jeff Beck",286.27546,"blues-rock","A Day In The Life (Album Version)");
        new Song("Taboo",301.71383,"new beat","Sous la Tour Eiffel");
        new Song("BigElf",298.13506,"stoner rock","Falling Bombs");
        new Song("Tanto Metro & Devonte",207.56853,"dancehall","Sometimes");
        new Song("Ray Kane",107.7024,"island music","Wa'ahila (Instrumental - Bonus Track)");
        new Song("Ashes to Ashes",254.32771,"avantgarde metal","Drive In Saturday - (Tribute to David Bowie)");
        new Song("Kelly Clarkson",230.63465,"teen pop","My Life Would Suck Without You");
        new Song("Fudge Tunnel",124.94322,"sludge metal","Bed Crumbs");
        new Song("Edgar Bori",264.61995,"los angeles","J'l'ai pas dit");
        new Song("Jimmy Witherspoon",147.69587,"jazz blues","I'm Just Wonderin' Part 2,");
        new Song("Eliane Elias",326.42567,"brazilian jazz","No More Blues (Chega de Saudade)");
        new Song("Dave Eggar",225.04444,"new age","Wave");
        new Song("Donnie Brooks",174.34077,"oldies","What'd I Say");
        new Song("2raumwohnung",357.85098,"tech house","Ja (Hanno's Poppersmonstermix)");
        new Song("SOJA",235.17995,"roots reggae","Time to come true");
        new Song("Dinosaur Jr.",271.12444,"indie rock","Whatever's Cool With Me (LP Version)");
        new Song("Ulytau",233.76934,"folk metal","Winter (Four Seasons)");
        new Song("The Nelons",200.202,"ccm","Hallelujah");
        new Song("The Exies",201.87383,"post-grunge","Creeper Kamikaze");
        new Song("Babylon Disco",208.90077,"breakcore","Error");
        new Song("Kaija Koo",227.36934,"humppa","Seuraavassa elA$?mA$?ssA$?");
        new Song("Gus Viseur",180.00934,"gypsy jazz","Fausse monnaie");
        new Song("Dino",245.39383,"ccm","Chariots Of Fire");
        new Song("GG Allin",121.70404,"shock rock","I Live to Be Hated");
        new Song("Zimbabwe Legit",235.91138,"hip hop","Siyabonga (Unreleased Bonus Track)");
        new Song("Spinal Tap",235.41506,"parody","The Majesty Of Rock");
        new Song("Der Moderne Man",159.55546,"new wave","Blaue Matrosen (live)");
        new Song("Buzzcocks",219.19302,"new wave","Strange Thing");
        new Song("Stanley Clarke",282.69669,"jazz funk","Journey To Love");
        new Song("La Portuaria",148.00934,"disco","Alguna Vez");
        new Song("Hemdale",107.57179,"grindcore","Rotting Fumes");
        new Song("Jesse Malin and The St. Marks Social",243.722,"urban folk","Revelations");
        new Song("3 Doors Down",230.42567,"post-grunge","It's Not Me");
        new Song("Ma Rainey",188.94322,"classic female blues","Ma Rainey's Black Bottom");
        new Song("Zombie Girl",260.54485,"electro","I Want It");
        new Song("Daniel Johnston",311.53587,"power pop","Story Of An Artist (Don't Be Scared)");
        new Song("Niraj Chag",262.5824,"trip hop","Sajana (Ft Faheem Mazhar)");
        new Song("JoAPSo Gilberto",197.19791,"brazilian jazz","Segredo");
        new Song("Bone Thugs-N-Harmony",255.73832,"gangster rap","Murder One");
        new Song("Ultraviolence",367.41179,"gabba","I Destructor (Lenny Dee Mix)");
        new Song("Los Chichos",191.68608,"flamenco","No Quieras Marcharte");
        new Song("Christian McBride",692.06159,"jazz funk","D Shuffle Jam (Part 2)");
        new Song("Jim Kweskin",208.90077,"ragtime","When I Was A Cowboy (Western Plains) (LP Version)");
        new Song("Utopia",239.59465,"new beat","On My Feet Again");
        new Song("Foxy Brown",222.92853,"hip hop","If I...");
        new Song("Muse",156.96934,"art rock","Bedroom Acoustics");
        new Song("String Trio Of New York",392.4371,"chamber jazz","Ju Ju");
        new Song("Enthroned",89.15546,"black metal","Ad Te Clamamus Exsvles Mortva Liberi");
        new Song("Mastodon",280.21506,"alternative metal","Deep Sea Creature");
        new Song("RamA3n Vargas;Vladimir Jurowski",278.38649,"opera","Werther - Lyric Drama in four Acts/Act I/Alors_ c'est bien ici la maison du bailli?");
        new Song("Portable",362.60526,"post-grunge","Theresa");
        new Song("Hank Locklin",146.83383,"honky tonk","Danny Boy");
        new Song("Lili Ivanova",253.70077,"pop folk","Pak shte te obicham");
        new Song("Wailing Souls",204.85179,"roots reggae","Old Broom");
        new Song("Furry Lewis",171.49342,"country blues","Good Looking Girl Blues");
        new Song("BrAPderna Djup",126.6673,"folk","RAY=skevA$?rsrock");
        new Song("Jo-El Sonnier",233.01179,"bluegrass","Cajun Blood");
        new Song("Naughty By Nature;Naughty By Nature featuring Zhane",213.91628,"gangster rap","Jamboree");
        new Song("Murskahumppa",145.76281,"suomi rock","Poikamies (2009)");
        new Song("Vanessa Bell Armstrong",231.54893,"gospel","Til The Victory's Won");
        new Song("Radiohead",267.20608,"british pop","Subterranean Homesick Alien");
        new Song("Dave Hollister",305.34485,"motown","Tell Me Why");
        new Song("Seamus Egan",205.21751,"irish folk","Lullaby");
        new Song("Arthur Tracy",161.38404,"vaudeville","Dance_ Gypsy_ Dance");
        new Song("Angelo Badalamenti",168.51546,"chill-out","Love Me");
        new Song("C.C. Adcock",121.0771,"zydeco","Good Loving");
        new Song("DMX",222.09261,"hip hop","Damien");
        new Song("James Horner",269.7922,"rock","The President's Speech");
        new Song("Kitaro",43.51955,"chill-out","Trong Com");
        new Song("Las Ketchup",171.80689,"rumba","Doble Bombo");
        new Song("C-Side & Petit Mal",212.47955,"country rock","Mudhump");
        new Song("Don Gibson",152.58077,"country rock","A Legend In My Time");
        new Song("Jewel",529.91955,"stoner metal","Serve The Ego (Hani Num Dub)");
        new Song("John Legend [feat. Buju Banton]",184.73751,"lovers rock","Fall In Love [Rub A Dub Mix]");
        new Song("Izzy",277.10649,"opera","Going Home");
        new Song("Nick Cave & The Bad Seeds",283.74159,"rock","Still In Love");
    }
}
